### PR TITLE
Capture form styling and refactoring

### PR DESCRIPTION
**Pull request by seadubs**
Refactored form sections into separate components
Added tabbed interface for basic vs advanced captures
Unified button / header styling across pages
Unified sidebar width across pages

image

### CODE REVIEW

**Comment by seadubs** [comment]
Note: setCapId linting issue will be resolved in a future PR when I migrate the capId/appId state to Redux.

**Review by 8000meters — DISMISSED** [review]
Looks bootiful. This is really nitpicky, but my only suggestion would be changing the color of the remove button to something that makes it the least obvious button on the page. Something like Outline-primary, or outline-secondary. Right now it kinda grabs your attention which I dont think we want.

**Comment by seadubs** [comment]
How about this, @8000meters?
image

**Review by 8000meters — APPROVED** [review]
❤️❤️❤️

**Pull request merged**
